### ISSUE TITLE
Uncaught IndexError: list index out of range


### ISSUE THREAD

**Issue by Sirbay** [DHI-GRAS/qgis-processing-workflow#17]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/hp/.qgis2/python/plugins\processing_workflow\WorkflowCreatorDialog.py", line 171, in runWorkflow
    self.workflow.run()
  File "C:/Users/hp/.qgis2/python/plugins\processing_workflow\Workflow.py", line 127, in run
    step = self._steps[0]
IndexError: list index out of range

```
processing_workflow 1.3.2, QGIS 2.18.28 on Windows 10

**Comment by radosuav** [comment]
Please provide detailed steps to reproduce.

Also, if you are using QGIS 3 you can try the new version of the plugin. It is marked as experimental at the moment so you will need to tick the "Show also experimental plugins" box in the Settings tab of Plugins dialog.
